sudo: false

services:
  - mongodb
  - memcache

rvm:
  - 2.0.0
  - 2.1.10
  - 2.2.10
  - 2.3.7
  - 2.4.6
  - 2.5.5
  - 2.6.3

env:
  - MONGOID_VERSION=3
  - MONGOID_VERSION=4
  - MONGOID_VERSION=5
  - MONGOID_VERSION=6
  - MONGOID_VERSION=7

cache: bundler

matrix:
  exclude:
    - rvm: 2.0.0
      env: MONGOID_VERSION=6
    - rvm: 2.1.10
      env: MONGOID_VERSION=6
    - rvm: 2.0.0
      env: MONGOID_VERSION=7
    - rvm: 2.1.10
      env: MONGOID_VERSION=7
  allow_failures:
    - env: MONGOID_VERSION=7
